- name: 'Add repository PHP 5.5 (Ondřej Surý PPA)'
  apt_repository: repo='ppa:ondrej/php5'

- name: 'PHP + libraries installed'
  apt: pkg={{ item }} state=latest
  with_items:
    - php5-fpm
    - php5-cli
    - php5-intl
    - php5-json
    - php5-curl
    - php5-mcrypt
    - php5-gd
    - php5-pgsql
    - php5-mysql
    - php-pear
  tags: php

- name: Enable php modules
  shell: php5enmod {{ item }}
  with_items:
    - mcrypt
  notify:
    - restart phpfpm
  tags: php

- name: Configure PHP settings
  template: src=php.ini dest=/etc/php5/fpm/conf.d/custom.ini  
  notify:
    - restart phpfpm
  tags: php

- name: Configure PHP-FPM Pool settings
  template: src=www-pool.j2 dest=/etc/php5/fpm/pool.d/www.conf
  notify:
    - restart phpfpm
  tags: php

- name: Chown PHP-FPM sessions dir
  shell: chown {{ username }}:{{ username }} /var/lib/php5 -Rf
  tags: php
