- name: Add official nginx repository
  apt_repository: repo='ppa:nginx/stable' state=present update_cache=yes
  tags: nginx

- name: Install Nginx
  apt: pkg=nginx state=latest
  tags: nginx

- name: Configure Nginx
  template: src=nginx.j2 dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx
  tags: nginx

- name: Configure Nginx Virtual hosts
  template: src=site.conf dest=/etc/nginx/sites-available/{{ item.name }}.conf
  with_items: vhosts
  notify:
    - restart nginx
  tags: nginx

- name: Disable default config
  file: path={{ item }} state=absent
  with_items:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
  notify:
    - restart nginx

- name: Enable config sites
  file: src=/etc/nginx/sites-available/{{ item.name }}.conf dest=/etc/nginx/sites-enabled/{{ item.name }}.conf state=link
  with_items: vhosts
  notify:
    - restart nginx